// Code generated by protoc-gen-go. DO NOT EDIT.
// source: movie.proto

package moviegrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MovieListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MovieListRequest) Reset()         { *m = MovieListRequest{} }
func (m *MovieListRequest) String() string { return proto.CompactTextString(m) }
func (*MovieListRequest) ProtoMessage()    {}
func (*MovieListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{0}
}

func (m *MovieListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieListRequest.Unmarshal(m, b)
}
func (m *MovieListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieListRequest.Marshal(b, m, deterministic)
}
func (m *MovieListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieListRequest.Merge(m, src)
}
func (m *MovieListRequest) XXX_Size() int {
	return xxx_messageInfo_MovieListRequest.Size(m)
}
func (m *MovieListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MovieListRequest proto.InternalMessageInfo

type MovieListResponse struct {
	Movies               []*GetMovieResponse `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MovieListResponse) Reset()         { *m = MovieListResponse{} }
func (m *MovieListResponse) String() string { return proto.CompactTextString(m) }
func (*MovieListResponse) ProtoMessage()    {}
func (*MovieListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{1}
}

func (m *MovieListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieListResponse.Unmarshal(m, b)
}
func (m *MovieListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieListResponse.Marshal(b, m, deterministic)
}
func (m *MovieListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieListResponse.Merge(m, src)
}
func (m *MovieListResponse) XXX_Size() int {
	return xxx_messageInfo_MovieListResponse.Size(m)
}
func (m *MovieListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MovieListResponse proto.InternalMessageInfo

func (m *MovieListResponse) GetMovies() []*GetMovieResponse {
	if m != nil {
		return m.Movies
	}
	return nil
}

type GetMovieRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMovieRequest) Reset()         { *m = GetMovieRequest{} }
func (m *GetMovieRequest) String() string { return proto.CompactTextString(m) }
func (*GetMovieRequest) ProtoMessage()    {}
func (*GetMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{2}
}

func (m *GetMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMovieRequest.Unmarshal(m, b)
}
func (m *GetMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMovieRequest.Marshal(b, m, deterministic)
}
func (m *GetMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMovieRequest.Merge(m, src)
}
func (m *GetMovieRequest) XXX_Size() int {
	return xxx_messageInfo_GetMovieRequest.Size(m)
}
func (m *GetMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMovieRequest proto.InternalMessageInfo

func (m *GetMovieRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetMovieResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Poster               string   `protobuf:"bytes,3,opt,name=poster,proto3" json:"poster,omitempty"`
	MovieUrl             string   `protobuf:"bytes,4,opt,name=movie_url,json=movieUrl,proto3" json:"movie_url,omitempty"`
	IsPaid               bool     `protobuf:"varint,5,opt,name=is_paid,json=isPaid,proto3" json:"is_paid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMovieResponse) Reset()         { *m = GetMovieResponse{} }
func (m *GetMovieResponse) String() string { return proto.CompactTextString(m) }
func (*GetMovieResponse) ProtoMessage()    {}
func (*GetMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{3}
}

func (m *GetMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMovieResponse.Unmarshal(m, b)
}
func (m *GetMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMovieResponse.Marshal(b, m, deterministic)
}
func (m *GetMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMovieResponse.Merge(m, src)
}
func (m *GetMovieResponse) XXX_Size() int {
	return xxx_messageInfo_GetMovieResponse.Size(m)
}
func (m *GetMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMovieResponse proto.InternalMessageInfo

func (m *GetMovieResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetMovieResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetMovieResponse) GetPoster() string {
	if m != nil {
		return m.Poster
	}
	return ""
}

func (m *GetMovieResponse) GetMovieUrl() string {
	if m != nil {
		return m.MovieUrl
	}
	return ""
}

func (m *GetMovieResponse) GetIsPaid() bool {
	if m != nil {
		return m.IsPaid
	}
	return false
}

func init() {
	proto.RegisterType((*MovieListRequest)(nil), "moviegrpc.MovieListRequest")
	proto.RegisterType((*MovieListResponse)(nil), "moviegrpc.MovieListResponse")
	proto.RegisterType((*GetMovieRequest)(nil), "moviegrpc.GetMovieRequest")
	proto.RegisterType((*GetMovieResponse)(nil), "moviegrpc.GetMovieResponse")
}

func init() { proto.RegisterFile("movie.proto", fileDescriptor_fde087a4194eda75) }

var fileDescriptor_fde087a4194eda75 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0xbd, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0x49, 0x1b, 0x92, 0xab, 0x04, 0xe5, 0x06, 0xb0, 0x52, 0x86, 0xe0, 0x29, 0x53, 0x86,
	0xf6, 0x19, 0x10, 0x1d, 0x40, 0x42, 0x96, 0x98, 0xab, 0x80, 0x2d, 0x64, 0xa9, 0xad, 0x8d, 0xed,
	0xf2, 0x04, 0x3c, 0x04, 0x8f, 0x8b, 0x38, 0x9a, 0x52, 0x45, 0x51, 0x37, 0xdf, 0x7d, 0x3f, 0xba,
	0xef, 0x33, 0x4c, 0x36, 0xf6, 0xd3, 0xe8, 0xc6, 0x79, 0x1b, 0x2d, 0x16, 0x34, 0xbc, 0x7b, 0xf7,
	0x26, 0x10, 0xa6, 0x4f, 0xbf, 0xc3, 0xa3, 0x09, 0x51, 0xea, 0x8f, 0x9d, 0x0e, 0x51, 0x2c, 0xe1,
	0xea, 0x68, 0x17, 0x9c, 0xdd, 0x06, 0x8d, 0x0b, 0xc8, 0x48, 0x15, 0x38, 0xab, 0xd2, 0x7a, 0x32,
	0x9f, 0x35, 0x07, 0x93, 0xe6, 0x41, 0x47, 0x12, 0x74, 0x64, 0xb9, 0xa7, 0x8a, 0x3b, 0xb8, 0xfc,
	0xc7, 0xc8, 0x1c, 0x2f, 0x20, 0x31, 0x8a, 0xb3, 0x8a, 0xd5, 0xa9, 0x4c, 0x8c, 0x12, 0x5f, 0x0c,
	0xa6, 0x7d, 0x7d, 0x9f, 0x84, 0x08, 0xa3, 0x6d, 0xbb, 0xd1, 0x3c, 0xa9, 0x58, 0x5d, 0x48, 0x7a,
	0xe3, 0x35, 0x64, 0xce, 0x86, 0xa8, 0x3d, 0x4f, 0x69, 0xbb, 0x9f, 0x70, 0x06, 0x7f, 0xf1, 0x56,
	0x3b, 0xbf, 0xe6, 0x23, 0x82, 0x72, 0x5a, 0xbc, 0xf8, 0x35, 0xde, 0xc0, 0xb9, 0x09, 0x2b, 0xd7,
	0x1a, 0xc5, 0xc7, 0x15, 0xab, 0x73, 0x99, 0x99, 0xf0, 0xdc, 0x1a, 0x35, 0xff, 0x66, 0x30, 0xa6,
	0x1b, 0xf0, 0x1e, 0xf2, 0xee, 0x1e, 0x2c, 0x07, 0x43, 0x52, 0x90, 0xf2, 0x54, 0x01, 0xe2, 0x0c,
	0x97, 0x50, 0x1c, 0x4a, 0xc4, 0x63, 0x6e, 0xbf, 0xee, 0xf2, 0x76, 0x18, 0xec, 0x9c, 0x5e, 0x33,
	0xfa, 0xb4, 0xc5, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x01, 0x1b, 0xf9, 0xf1, 0xc3, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MovieClient is the client API for Movie service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MovieClient interface {
	GetMovie(ctx context.Context, in *GetMovieRequest, opts ...grpc.CallOption) (*GetMovieResponse, error)
	MovieList(ctx context.Context, in *MovieListRequest, opts ...grpc.CallOption) (*MovieListResponse, error)
}

type movieClient struct {
	cc *grpc.ClientConn
}

func NewMovieClient(cc *grpc.ClientConn) MovieClient {
	return &movieClient{cc}
}

func (c *movieClient) GetMovie(ctx context.Context, in *GetMovieRequest, opts ...grpc.CallOption) (*GetMovieResponse, error) {
	out := new(GetMovieResponse)
	err := c.cc.Invoke(ctx, "/moviegrpc.Movie/GetMovie", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieClient) MovieList(ctx context.Context, in *MovieListRequest, opts ...grpc.CallOption) (*MovieListResponse, error) {
	out := new(MovieListResponse)
	err := c.cc.Invoke(ctx, "/moviegrpc.Movie/MovieList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MovieServer is the server API for Movie service.
type MovieServer interface {
	GetMovie(context.Context, *GetMovieRequest) (*GetMovieResponse, error)
	MovieList(context.Context, *MovieListRequest) (*MovieListResponse, error)
}

// UnimplementedMovieServer can be embedded to have forward compatible implementations.
type UnimplementedMovieServer struct {
}

func (*UnimplementedMovieServer) GetMovie(ctx context.Context, req *GetMovieRequest) (*GetMovieResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMovie not implemented")
}
func (*UnimplementedMovieServer) MovieList(ctx context.Context, req *MovieListRequest) (*MovieListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MovieList not implemented")
}

func RegisterMovieServer(s *grpc.Server, srv MovieServer) {
	s.RegisterService(&_Movie_serviceDesc, srv)
}

func _Movie_GetMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServer).GetMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moviegrpc.Movie/GetMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServer).GetMovie(ctx, req.(*GetMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Movie_MovieList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MovieListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServer).MovieList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moviegrpc.Movie/MovieList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServer).MovieList(ctx, req.(*MovieListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Movie_serviceDesc = grpc.ServiceDesc{
	ServiceName: "moviegrpc.Movie",
	HandlerType: (*MovieServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMovie",
			Handler:    _Movie_GetMovie_Handler,
		},
		{
			MethodName: "MovieList",
			Handler:    _Movie_MovieList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "movie.proto",
}
